/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AircraftCallsignRoute: typeof import('./components/Routes/Get/AircraftCallsignRoute.vue')['default']
    AircraftPatch: typeof import('./components/Routes/Patch/AircraftPatch.vue')['default']
    AircraftRoute: typeof import('./components/Routes/Get/AircraftRoute.vue')['default']
    AircraftTable: typeof import('./components/Tables/AircraftTable.vue')['default']
    AirlineRoute: typeof import('./components/Routes/Get/AirlineRoute.vue')['default']
    AirlineTable: typeof import('./components/Tables/AirlineTable.vue')['default']
    AppCard: typeof import('./components/AppCard.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AppThanks: typeof import('./components/AppThanks.vue')['default']
    CallsignPatch: typeof import('./components/Routes/Patch/CallsignPatch.vue')['default']
    CallsignRoute: typeof import('./components/Routes/Get/CallsignRoute.vue')['default']
    CodeBlock: typeof import('./components/CodeBlock.vue')['default']
    ExternalLink: typeof import('./components/ExternalLink.vue')['default']
    FlightrouteTable: typeof import('./components/Tables/FlightrouteTable.vue')['default']
    GenericTable: typeof import('./components/Tables/GenericTable.vue')['default']
    GetRoutes: typeof import('./components/Routes/GetRoutes.vue')['default']
    GotoTD: typeof import('./components/Tables/GotoTD.vue')['default']
    MidPoint: typeof import('./components/Tables/MidPoint.vue')['default']
    ModeSRoute: typeof import('./components/Routes/Get/ModeSRoute.vue')['default']
    NNumberRoute: typeof import('./components/Routes/Get/NNumberRoute.vue')['default']
    OnlineRoute: typeof import('./components/Routes/Get/OnlineRoute.vue')['default']
    OnlineStatus: typeof import('./components/OnlineStatus.vue')['default']
    PatchRoutes: typeof import('./components/Routes/PatchRoutes.vue')['default']
    RateLimits: typeof import('./components/RateLimits.vue')['default']
    RouteDescription: typeof import('./components/Routes/RouteDescription.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SnackBar: typeof import('./components/SnackBar.vue')['default']
    StatsRoute: typeof import('./components/Routes/Get/StatsRoute.vue')['default']
    TableResponse: typeof import('./components/Tables/TableResponse.vue')['default']
    UpArrow: typeof import('./components/UpArrow.vue')['default']
    UrlBox: typeof import('./components/UrlBox.vue')['default']
  }
}
